Fixed mouse interaction with user. However, this push introduced an "undefined reference to"
- Was not able to fix this "undefined reference to" error.
We should look into this